### PR TITLE
Update to 0.26.1

### PR DESCRIPTION
**Pull request by wmoxam**
0.26.1 Release note here: https://crystal-lang.org/2018/08/27/crystal-0.26.1-released.html

* Bootstrap object has been rebuilt and now hosted at wmoxam.com again

### CODE REVIEW

**Comment by wmoxam** [comment]
@jcs Any chance you can test this out on `current`?

I'm having problems with dev machine and was only able to test on `6.3`

**Comment by jcs** [comment]
It looks like shards' makefile won't take options from the environment anymore, so it needs them as args:

````
Using compiled compiler at `.build/crystal'
/usr/local/lib/libevent_core.so.1.1: warning: random() may return deterministic values, is that what you want?
/usr/local/lib/libLLVM-6.0.so: warning: strcpy() is almost always misused, please use strlcpy()
/usr/local/lib/libevent_core.so.1.1: warning: random() may return deterministic values, is that what you want?
/usr/local/lib/libLLVM-6.0.so: warning: sprintf() is often misused, please use snprintf()
cd /usr/ports/pobj/crystal-0.26.1/crystal-0.26.1/../shards-0.8.1 &&  CRYSTAL=/usr/ports/pobj/crystal-0.26.1/crystal-0.26.1/.build/crystal CRFLAGS=--release  gmake
crystal build src/shards.cr -o bin/shards 
gmake: crystal: Command not found
gmake: *** [Makefile:21: bin/shards] Error 127
*** Error 2 in . (Makefile:73 'do-build')
*** Error 1 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2726 '/usr/ports/pobj/crystal-0.26.1/.build_done')
*** Error 1 in /usr/ports/crystal-openbsd-port/lang/crystal (/usr/ports/infrastructure/mk/bsd.port.mk:2409 'all')
````

Moving things to args gets it pointed at the right crystal binary, but it won't build now:

````
cd /usr/ports/pobj/crystal-0.26.1/crystal-0.26.1/../shards-0.8.1 &&  gmake CRYSTAL=/usr/ports/pobj/crystal-0.26.1/crystal-0.26.1/.build/crystal  CRFLAGS=--release
/usr/ports/pobj/crystal-0.26.1/crystal-0.26.1/.build/crystal build src/shards.cr -o bin/shards --release
Error in src/shards.cr:1: while requiring "prelude": can't find file 'prelude'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "./config"
^

gmake: *** [Makefile:21: bin/shards] Error 1
````

**Comment by jcs** [comment]
FYI, ports will probably lock for 6.4 soon, so if the 26.1 update won't be ready, I'd recommend just recompiling the 0.25.1 bootstrap object on a -current build, calling it `crystal-0.25.1-OpenBSD6.4.tar.gz`, and then add `REVISION = 0`.  Then mail that diff to ports@openbsd.org to get it committed before the freeze.

**Comment by wmoxam** [comment]
Submitted a patch to the mailing list: https://marc.info/?l=openbsd-ports&m=153866173218310&w=2

The code here is somewhat out of sync with what was in the tree, I ended up applying changes to code from the tree which resulted in a smaller diff. Compiled and tested on a recent snapshot, everything seemed good.

**Pull request closed without merging**
