### PR TITLE
Update to 0.25.1, shards to 0.8.1

### PR DESCRIPTION
**Pull request by jcs**
- ~~Add MAP_STACK patches which are pending upstream commit (https://github.com/crystal-lang/crystal/pull/6250)~~ `MAP_STACK` patch was accepted upstream for the 0.25.1 release
- Bootstrap object has been rebuilt and temporarily hosted at jcs.org
- Crank stack and data size resource limits before building compiler or else it will SIGSEGV
- Wrap DESCR at 68

### CODE REVIEW

**Comment by jcs** [comment]
The bash change is no longer needed because upstream got rid of the bash'isms after 0.24.2, and this has the `MAP_STACK` patches mentioned in my previous PR (#12) but updated from the current upstream PR.

If/when you submit this to ports@, you should adjust `MASTER_SITES0` back to your server.

**Comment by jcs** [comment]
Updated to 0.25.1, no longer needs any patches.

**Comment by jcs** [comment]
Will you be submitting this to ports@ soon?  I think it's in good enough shape to at least get feedback from the porters.  If not, I'd like to submit it and I can leave you as `MAINTAINER` or make it blank.

**Comment by wmoxam** [comment]
@jcs If you'd like to submit it that's fine with me. I'm ok with leaving me as the `MAINTAINER`

Thanks!

**Review by wmoxam — APPROVED** [review]

**Comment by jcs** [comment]
@wmoxam The port has been imported:

https://marc.info/?l=openbsd-ports-cvs&m=153106003111089&w=2

**Pull request merged**
